public class DemoApex {

    public static void method1 () {
        Boolean isActive=true;
        system.debug('Value is Active ='+isActive);
    }
    
       public static void method2 () {
        String fName='sankalp';
        String lName='Lokhande';
        system.debug('Full Name ='+fName+' '+lName);
    }
    
    public static void method3(){
        ID accId='006dM00000GGFl3QAH';
        system.debug('Account Id is ='+accId);
    }
}