public class Rectangle {
     //Method
    public void area() {
        Decimal length =5.5, breadth=6; //variables creation.
        Decimal a = (length*breadth) ;
        System.debug('Area =' + a);
      }

      //Method
    public void parimeter() {
        Decimal length =5.5, breadth=6; //variables creation.
        Decimal p = 2*(length*breadth) ;
        System.debug('parimeter =' + p);
      }
}