public class Cal {
    
    Public static void add(Integer S1,Integer S2){               //Method1
        Integer Num1=S1;
        Integer Num2=S2, Sum;
        Sum=Num1+Num2;
        System.debug('sum is ='+sum); 
    }
    
    
    

        Public static void sub(Integer l1,Integer l2){
        Integer Num=l1;
        Integer Num1=l2, Sub;
        Sub=Num-Num1;
        System.debug('sub is ='+sub); 
    }
    
        Public static void mul(){
        Integer Num=10;
        Integer Num1=20, mul;
        mul=Num*Num1;
        System.debug('sum is ='+mul); 
    }

}